<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tony DiRubbo">

<title>Predicting Heart Disease with Machine Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="PortfolioWithPictures_files/libs/clipboard/clipboard.min.js"></script>
<script src="PortfolioWithPictures_files/libs/quarto-html/quarto.js"></script>
<script src="PortfolioWithPictures_files/libs/quarto-html/popper.min.js"></script>
<script src="PortfolioWithPictures_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PortfolioWithPictures_files/libs/quarto-html/anchor.min.js"></script>
<link href="PortfolioWithPictures_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PortfolioWithPictures_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PortfolioWithPictures_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PortfolioWithPictures_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PortfolioWithPictures_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Heart Disease with Machine Learning</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tony DiRubbo </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p><img src="images/Coronary-disease-illustration-1200x982.jpg" class="img-fluid">Heart disease can pertain to a range of conditions that affect the heart and its purpose of pumping blood throughout the body. Generally, heart disease is diagnosed when direct blood flow to the heart, before it is pumped by the heart to the rest of the body, is compromised. Since the 1950’s heart disease has been the leading cause of death in America. The Center for Disease Control (CDC) estimates that one person dies of heart disease around every 33 seconds.</p>
<p>The UC Irvine Machine Learning Repository has provided access to four databases. Two in America, a Cleveland hospital and the VA in Long Beach, California, as well as hospitals in Hungary and Switzerland. The four databases can be combined imported in Python, then combined using SQL to make one complete dataset. The dataset has hundreds of observations and 14 variables. For each patient: age, sex, cerebral palsy, resting blood pressure, cholesterol, fasting blood sugar above 120mg/dl , resting cardiography measurement, maximum heart rate, exercised induced angina, presence of ST depression, heart rate slope, number of blood vessels colored in a fluoroscopy, thalassemia diagnoses, as well as if the doctors at each corresponding hospital diagnosed the patient with heart disease.</p>
<p>The dataset can be found at: https://archive.ics.uci.edu/dataset/45/heart+disease</p>
<p>The following are the required packages for the entire analyses:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">081302</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret) <span class="co">#for knn, trees, regression, ANN</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caretEnsemble) <span class="co"># for regression</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co">#for cleaning data</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(earth) <span class="co"># for regression</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot) <span class="co"># for plotting</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co">#for plotting</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet) <span class="co">#for regression</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)<span class="co">#for regression</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kernlab) <span class="co"># for regression</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlbench) <span class="co">#for trees, regression</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(neuralnet) <span class="co"># for ANN</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(party) <span class="co">#for trees</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(partykit) <span class="co">#for trees</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC) <span class="co">#for knn</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest) <span class="co">#for regression</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr) <span class="co">#for reading data</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart) <span class="co"># for regression</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr) <span class="co">#for examining data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="feature-engineering-of-data" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering-of-data">Feature Engineering of Data</h2>
<p>For simplifying conclusions, the heart disease diagnoses will be binned so that a patient is either diagnosed with heart disease or not (two options). Variables will be renamed so that they are easier to interpret in code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>HDdf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"heart_disease_uci.csv"</span>) <span class="co">#reading in the CSV</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Updates data so that heart disease diagnoses is a two factor variable</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>HDdf <span class="ot">&lt;-</span> <span class="fu">within</span>(HDdf,{num<span class="ot">&lt;-</span><span class="fu">factor</span>(num, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,<span class="st">"Yes"</span>,<span class="st">"Yes"</span>,<span class="st">"Yes"</span>,<span class="st">"Yes"</span>))}) </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#renaming variables so that they are easier to understand at a quick glance</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"cp"</span>] <span class="ot">&lt;-</span> <span class="st">"CerebralPalsy"</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"chol"</span>] <span class="ot">&lt;-</span> <span class="st">"Cholestoral"</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"fbs"</span>] <span class="ot">&lt;-</span> <span class="st">"FastingBloodSugar"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"restecg"</span>] <span class="ot">&lt;-</span> <span class="st">"RestingECGReading"</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"exang"</span>] <span class="ot">&lt;-</span> <span class="st">"ExercisedAngina"</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"trestbps"</span>] <span class="ot">&lt;-</span> <span class="st">"RestingBPS"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"thalch"</span>] <span class="ot">&lt;-</span> <span class="st">"MaxHeartRate"</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"oldpeak"</span>] <span class="ot">&lt;-</span> <span class="st">"STDepression"</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"slope"</span>] <span class="ot">&lt;-</span> <span class="st">"STSlope"</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"ca"</span>] <span class="ot">&lt;-</span> <span class="st">"FluoroscopyColoredVessels"</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"thal"</span>] <span class="ot">&lt;-</span> <span class="st">"ThalassemiaDiagnoses"</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDdf)[<span class="fu">names</span>(HDdf) <span class="sc">==</span> <span class="st">"num"</span>] <span class="ot">&lt;-</span> <span class="st">"HeartDisease"</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co">#saves data as a data frame</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>HDdf <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(HDdf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Basic summary statistics can be conducted to gather a better understanding of the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(HDdf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">HDdf</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">920</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">logical</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 26%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">CerebralPalsy</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RestingECGReading</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">STSlope</td>
<td style="text-align: right;">309</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ThalassemiaDiagnoses</td>
<td style="text-align: right;">486</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">HeartDisease</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Yes: 509, No: 411</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FastingBloodSugar</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: left;">FAL: 692, TRU: 138</td>
</tr>
<tr class="even">
<td style="text-align: left;">ExercisedAngina</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: left;">FAL: 528, TRU: 337</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 26%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">53.51</td>
<td style="text-align: right;">9.42</td>
<td style="text-align: right;">28.0</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">54.0</td>
<td style="text-align: right;">60.0</td>
<td style="text-align: right;">77.0</td>
<td style="text-align: left;">▁▅▇▆▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">RestingBPS</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">132.13</td>
<td style="text-align: right;">19.07</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">130.0</td>
<td style="text-align: right;">140.0</td>
<td style="text-align: right;">200.0</td>
<td style="text-align: left;">▁▁▅▇▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cholestoral</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">199.13</td>
<td style="text-align: right;">110.78</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">175</td>
<td style="text-align: right;">223.0</td>
<td style="text-align: right;">268.0</td>
<td style="text-align: right;">603.0</td>
<td style="text-align: left;">▃▇▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">MaxHeartRate</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">137.55</td>
<td style="text-align: right;">25.93</td>
<td style="text-align: right;">60.0</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">140.0</td>
<td style="text-align: right;">157.0</td>
<td style="text-align: right;">202.0</td>
<td style="text-align: left;">▁▃▇▇▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">STDepression</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">-2.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">6.2</td>
<td style="text-align: left;">▁▇▆▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">FluoroscopyColoredVessels</td>
<td style="text-align: right;">611</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: left;">▇▃▁▂▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>There are 920 observations among the 14 variables. Five of the variables are classified as characters: sex, cerebral palsy diagnoses, resting ecg reading, ST slope, and Thalassemia diagnoses. The resulting heart disease diagnosis is identified as a factor variable. Fasting Blood Sugar levels above 120 mg/dl and exercised induced Angina are true and false variables. Finally, age, resting heart rate, cholesterol, maximum heart rate, ST Depression scores, and colored vessels on a fluoroscopy are all numeric variables. For all missing observations for each dataset, the median value for those variables will be inputted so that further analyses can be conducted later, without decreasing the total number of observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>HDdf <span class="ot">&lt;-</span> HDdf <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(age), <span class="fu">median</span>(age, <span class="at">na.rm=</span><span class="cn">TRUE</span>), age),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">RestingBPS =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(RestingBPS), <span class="fu">median</span>(RestingBPS, <span class="at">na.rm=</span><span class="cn">TRUE</span>), RestingBPS),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Cholestoral =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(Cholestoral), <span class="fu">median</span>(Cholestoral, <span class="at">na.rm=</span><span class="cn">TRUE</span>), Cholestoral),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">MaxHeartRate =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(MaxHeartRate), <span class="fu">median</span>(MaxHeartRate, <span class="at">na.rm=</span><span class="cn">TRUE</span>), MaxHeartRate),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">STDepression =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(STDepression), <span class="fu">median</span>(STDepression, <span class="at">na.rm=</span><span class="cn">TRUE</span>), STDepression),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">FluoroscopyColoredVessels =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(FluoroscopyColoredVessels), <span class="fu">median</span>(FluoroscopyColoredVessels, <span class="at">na.rm=</span><span class="cn">TRUE</span>), FluoroscopyColoredVessels))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data frame will additionally be divided into various sections so that only the numerical and classification values can be analyzed independent from one another if deemed fit. Able variables will be turned into dummy variables so that they can be implemented into the regression analysis later on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#NumericVariablesOnly</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>HDn <span class="ot">&lt;-</span> <span class="fu">select</span>(HDdf, <span class="fu">c</span>(<span class="st">"age"</span>,<span class="st">"RestingBPS"</span>,<span class="st">"Cholestoral"</span>,<span class="st">"MaxHeartRate"</span>,<span class="st">"STDepression"</span>,<span class="st">"FluoroscopyColoredVessels"</span>,<span class="st">"HeartDisease"</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#RegressionVariables</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>HDreg <span class="ot">&lt;-</span> <span class="fu">select</span>(HDdf, <span class="fu">c</span>(<span class="st">"HeartDisease"</span>,<span class="st">"age"</span>,<span class="st">"RestingBPS"</span>,<span class="st">"Cholestoral"</span>,<span class="st">"MaxHeartRate"</span>,<span class="st">"STDepression"</span>,<span class="st">"FluoroscopyColoredVessels"</span>,<span class="st">"sex"</span>,<span class="st">"FastingBloodSugar"</span>,<span class="st">"RestingECGReading"</span>,<span class="st">"ExercisedAngina"</span>,<span class="st">"ThalassemiaDiagnoses"</span>))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating Dummy Variables for Regression (HDreg2)</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#ifelse(test_expression, x, y)</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>HDreg<span class="sc">$</span>HeartDisease<span class="ot">&lt;-</span><span class="fu">ifelse</span>(HDreg<span class="sc">$</span>HeartDisease <span class="sc">==</span> <span class="st">"Yes"</span>,<span class="fl">1.0</span>,<span class="dv">0</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDreg)[<span class="fu">names</span>(HDreg) <span class="sc">==</span> <span class="st">"sex"</span>] <span class="ot">&lt;-</span> <span class="st">"Male"</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>HDreg<span class="sc">$</span>Male<span class="ot">&lt;-</span><span class="fu">ifelse</span>(HDreg<span class="sc">$</span>Male <span class="sc">==</span> <span class="st">"Male"</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>HDreg<span class="sc">$</span>FastingBloodSugar<span class="ot">&lt;-</span><span class="fu">ifelse</span>(HDreg<span class="sc">$</span>FastingBloodSugar <span class="sc">==</span> <span class="cn">TRUE</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(HDreg)[<span class="fu">names</span>(HDreg) <span class="sc">==</span> <span class="st">"RestingECGReading"</span>] <span class="ot">&lt;-</span> <span class="st">"Hypertrophy"</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>HDreg<span class="sc">$</span>Hypertrophy<span class="ot">&lt;-</span><span class="fu">ifelse</span>(HDreg<span class="sc">$</span>Hypertrophy <span class="sc">==</span> <span class="st">"normal"</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>HDreg<span class="sc">$</span>ExercisedAngina<span class="ot">&lt;-</span><span class="fu">ifelse</span>(HDreg<span class="sc">$</span>ExercisedAngina <span class="sc">==</span> <span class="cn">TRUE</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>HDreg<span class="sc">$</span>ThalassemiaDiagnoses<span class="ot">&lt;-</span><span class="fu">ifelse</span>(HDreg<span class="sc">$</span>ThalassemiaDiagnoses <span class="sc">==</span> <span class="st">"normal"</span>,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Impute missing values with mean column-wise</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col <span class="cf">in</span> <span class="fu">names</span>(HDreg)) {</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  HDreg[<span class="fu">is.na</span>(HDreg[, col]), col] <span class="ot">&lt;-</span> <span class="fu">mean</span>(HDreg[, col], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="reminder-of-research-conjecture" class="level2">
<h2 class="anchored" data-anchor-id="reminder-of-research-conjecture">Reminder of Research Conjecture</h2>
<p>After examining the data frame and conducting initial cleaning, two research questions have arisen. The first question is a classification research question which asks presence of heart disease within patients based on these recorded variables and risk factors can be predicted. From the numeric variables, regression research questions can also be asked.</p>
<p>The planned regression research question will attempt to predict the percent chance an individual develops heart disease using the dummy variable of heart disease, and all other potential numeric/dummy variables in the data frame as independent variables. Multiple regression models will be developed at first, before the best model is selected and further analyzed.</p>
</section>
<section id="classification-with-trees" class="level2">
<h2 class="anchored" data-anchor-id="classification-with-trees">Classification with Trees</h2>
<p>Starting off with the classification question of predicting heart disease based on a variety of numerical factors, the conditional tree algorithm is a strong initial way to test our research conjecture. Trees create a set of rules and tunnels for a variable to pass through to create predictions. Initially A CTree1&amp;2 model was created, however due to strength of model, a CTree1 model will be generated because it will generate a larger number of nodes to examine. This is because a CTree1 model uses only binary partitioning.</p>
<p>Testing and training data will also be created, this separation of data will be kept consistent throughout the entire analysis. Some data needs to be seperated like this so that the created models are fit for the general population of interest, not just the analyzed data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">081302</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the control method</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method=</span><span class="st">"cv"</span>, <span class="at">n=</span><span class="dv">3</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># center and scale numeric variables then do pca for consistency</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>preProc <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># estimating the CTree1</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  m1_ctree <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data=</span>HDn, <span class="at">method=</span><span class="st">"ctree"</span>, <span class="at">trControl =</span> ctrl, <span class="at">preProcess=</span>preProc)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>((m1_ctree<span class="sc">$</span>finalModel), <span class="at">main =</span> <span class="st">"Ctree Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PortfolioWithPictures_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The CTree created nine nodes, of which seven lean in one direction more than 75% of the time (Nodes 4,6,9,10,14,15,16) and two of them do not appear better than random chance (Nodes 7,17). The tree splits observations first by maximum heart rate, then examines colored vessels in a fluoroscope for those with high heart rates. STDepression is then examined for all observations, then cholesterol, finally some remaining observations are separated by age before being placed in their respective node. This CTree gave a strong indicator of how predictions for Heart Disease are made before, continuing with other machine learning models.</p>
</section>
<section id="classification-with-nearest-neighbor-knn" class="level2">
<h2 class="anchored" data-anchor-id="classification-with-nearest-neighbor-knn">Classification with Nearest Neighbor (KNN)</h2>
<p>Using the CARET package we can simplify the process of using the KNN algorithm. In machine learning, known nearest neighbors refer to a technique used in classification, where the algorithm identifies the closest data points to a given point within a known data frame. Known nearest neighbors rely on the assumption that data points with similar features tend to exhibit similar behaviors or outcomes.</p>
<p><img src="images/0_2_qzcm2gSe9l67aI.png" class="img-fluid"></p>
<p>The first step will be calculated the starting k(number of neighbors):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">920</span>)<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.16575</code></pre>
</div>
</div>
<p>The calculation above suggests that 15 is the best starting k, so k’s from 1-30, increasing by 3 will be measured.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>k_values <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">k =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">9</span>,<span class="dv">12</span>,<span class="dv">15</span>,<span class="dv">18</span>,<span class="dv">21</span>,<span class="dv">24</span>,<span class="dv">27</span>,<span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data set needs to be spitted into testing data and training data so that over training does not occur, 80% of the data will be studied, while the remaining 20% will be used for predictions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">081302</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(HDn<span class="sc">$</span>HeartDisease, <span class="at">p =</span> .<span class="dv">8</span>, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">list =</span> <span class="cn">FALSE</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">times =</span> <span class="dv">1</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>HDdf_train <span class="ot">&lt;-</span> HDn[trainIndex,]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>HDdf_test <span class="ot">&lt;-</span> HDn[<span class="sc">-</span>trainIndex,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that the data is split we can run the KNN algorithm:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">081302</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method=</span><span class="st">"cv"</span>, <span class="at">n=</span><span class="dv">5</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>knnFit <span class="ot">&lt;-</span> <span class="fu">train</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> HDdf_train, <span class="at">method =</span> <span class="st">"knn"</span>, </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">trControl =</span> ctrl, <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"range"</span>), </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">tuneGrid=</span> k_values)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># print best k</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>knnFit<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   k
6 15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print results for each k tested</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>knnFit<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    k  Accuracy     Kappa AccuracySD    KappaSD
1   1 0.6810259 0.3537413 0.05959829 0.11717394
2   3 0.7299779 0.4514962 0.02777067 0.05611329
3   6 0.7449255 0.4814446 0.02956053 0.06225673
4   9 0.7530796 0.4960769 0.03446405 0.07112844
5  12 0.7652602 0.5224210 0.04129710 0.08520443
6  15 0.7801986 0.5535674 0.03402230 0.06921844
7  18 0.7557639 0.5040871 0.03768473 0.07786586
8  21 0.7625207 0.5180490 0.02937893 0.06018087
9  24 0.7652510 0.5242032 0.03409766 0.06912256
10 27 0.7611785 0.5159758 0.03818060 0.07843167
11 30 0.7584482 0.5110480 0.04595637 0.09388861</code></pre>
</div>
</div>
<p>The k-value which performed the best was the initially calculated k-value of 15. K=15 had an accuracy of 0.7802 and a Kappa of 0.5536. The accuracy value indicates that about 78% of the model’s predictions were correct. Kappa indicates that the model performed somewhere in the middle between perfectly identifying (kappa = 1) and selecting due to random chance (kappa = 0)</p>
<p>Now the model can examine the test data and make predictions</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>HDdf_test_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(knnFit, <span class="at">newdata =</span> HDdf_test)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate model performance in </span><span class="al">TESTING</span><span class="co"> sample</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(HDdf_test_pred, HDdf_test<span class="sc">$</span>HeartDisease)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction No Yes
       No  59  20
       Yes 23  81
                                          
               Accuracy : 0.765           
                 95% CI : (0.6968, 0.8244)
    No Information Rate : 0.5519          
    P-Value [Acc &gt; NIR] : 1.752e-09       
                                          
                  Kappa : 0.5233          
                                          
 Mcnemar's Test P-Value : 0.7604          
                                          
            Sensitivity : 0.7195          
            Specificity : 0.8020          
         Pos Pred Value : 0.7468          
         Neg Pred Value : 0.7788          
             Prevalence : 0.4481          
         Detection Rate : 0.3224          
   Detection Prevalence : 0.4317          
      Balanced Accuracy : 0.7607          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
</div>
<p>The model yielded a sensitivity of about 77% and a specificity of about 80%. 77% of heart disease diagnoses were correct, and 80% of confirmations that the patient did not have heart disease were correct. With heart disease both Type 1 and Type 2 errors are very crucial. A Type 2 error (failing to identify heart disease) is occurring less than a type 1 error (falsely identifying heart disease). The argument could be made that a type-2 error is more of a health risk whereas a type-1 error is more of a financial risk (paying for useless treatments) so having more type-1 errors is optimal.</p>
<section id="receiver---operator-curve" class="level3">
<h3 class="anchored" data-anchor-id="receiver---operator-curve">Receiver - Operator Curve</h3>
<p>The receiver - operator curve maps sensitivity and against false negativity rate (1 minus the specificity). The more area under the curve indicates a better performing model, with an area of 1 indicating perfect accuracy.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_obj, <span class="at">print.thres =</span> <span class="st">"best"</span>, <span class="at">print.thres.best.method =</span> <span class="st">"closest.topleft"</span>,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Receiver Operator Curve (ROC)"</span>, <span class="co"># Title</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>, <span class="co"># Color of the curve</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd =</span> <span class="dv">2</span>, <span class="co"># Line width</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.auc =</span> <span class="cn">TRUE</span>, <span class="co"># Display AUC value</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.auc.cex =</span> <span class="fl">1.5</span>, <span class="co"># AUC text size</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.auc.offset =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.1</span>), <span class="co"># AUC text offset</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.auc.just =</span> <span class="fu">c</span>(<span class="st">"left"</span>, <span class="st">"top"</span>), <span class="co"># AUC text justification</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.auc.col =</span> <span class="st">"black"</span>, <span class="co"># AUC text color</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.thres.pch =</span> <span class="dv">20</span>, <span class="co"># Threshold point shape</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.thres.col =</span> <span class="st">"red"</span>, <span class="co"># Threshold point color</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.thres.cex =</span> <span class="fl">1.2</span>, <span class="co"># Threshold point size</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.thres.adj =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>), <span class="co"># Threshold point text adjustment</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">col.thres =</span> <span class="st">"red"</span>, <span class="co"># Threshold line color</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.thres.pattern =</span> <span class="st">"/"</span>, <span class="co"># Threshold point pattern</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">print.thres.pattern.cex =</span> <span class="dv">1</span>, <span class="co"># Threshold point pattern size</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"False Positive Rate (1 - Specificity)"</span>, <span class="co"># X-axis label</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"True Positive Rate (Sensitivity)"</span>, <span class="co"># Y-axis label</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="fl">1.2</span>, <span class="co"># Axis label size</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.2</span>, <span class="co"># Axis tick label size</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.main =</span> <span class="fl">1.5</span>, <span class="co"># Title size</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.sub =</span> <span class="fl">1.2</span>, <span class="co"># Subtitle size</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">grid =</span> <span class="cn">TRUE</span> <span class="co"># Add grid</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>     )</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"ROC Curve"</span>), <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PortfolioWithPictures_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Area for this model is about .846, which is the highest indicator of the success of this knn model (sensitivity was about .80, and accuracy was about .77)</p>
</section>
</section>
<section id="regression" class="level2">
<h2 class="anchored" data-anchor-id="regression">Regression</h2>
<p>Regression models will be used to test the second research conjecture: the creation of a linear-probability model which will allow to predict the percent chance an individual develops heart disease(in decimal form, 100%=1,50%=.50). The CARET package will allow us to quickly create regression machine learning models which can be compared to find the best performing model for further analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>highlycorr<span class="ot">&lt;-</span> <span class="fu">findCorrelation</span>(<span class="fu">cor</span>(HDreg), <span class="at">cutoff =</span><span class="fl">0.80</span>)        </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>No variables were found to be highly correlated with each other so regression models can proceed without the worry of multicolinearity in the data frame.</p>
<section id="finding-the-proper-model" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-proper-model">Finding the Proper Model</h3>
<p>Seven types of regression models will be created and compared: 1. Basic linear regression 2. Decision Tree Regression - constructs a tree-like model by splitting the data based on various rules 3. Random Forest Regression - combines the predictions of multiple decision trees to reduce overfitting and improve accuracy. 4. Stepwise Regression - a regression method which employs both forward selection and backwards elimination of critical data points which will influence the regression. 5. Elastic Regression - an adaptable version of regression combining the “lasso” and “ridge” techniques. 6. MARS Regression Technique - a regression technique which consts of multiple piecewise functions. 7. Support Vector Machine - identifies a hyperplane with maximum margin between data points</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">081302</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data partitions</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(HDreg<span class="sc">$</span>HeartDisease, <span class="at">p =</span> .<span class="dv">8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>, <span class="at">times =</span> <span class="dv">1</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> HDreg[trainIndex,]</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> HDreg[<span class="sc">-</span>trainIndex,]</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define control method for all future regression models</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"repeatedcv"</span>, <span class="at">repeats =</span> <span class="dv">3</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Define tuning grids for models</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>grid_rpart <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">cp =</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.5</span>, <span class="fl">0.05</span>))</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>grid_rf <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">mtry =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">ncol</span>(train_data) <span class="sc">-</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="dv">3</span>))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>grid_mars <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">degree =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">nprune =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>grid_nn <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">layer1=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">layer2=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">layer3=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>))</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>grid_svm <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">sigma =</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.2</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="at">C =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">5</span>, <span class="at">to =</span> <span class="dv">15</span>, <span class="at">by =</span> <span class="dv">5</span>)))</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Train individual models</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">caretList</span>(</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> train_data,</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> ctrl,  <span class="co"># Corrected typo here</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">preProcess =</span> <span class="fu">c</span>(<span class="st">"center"</span>, <span class="st">"scale"</span>),</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric =</span> <span class="st">"Rsquared"</span>,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">tuneList =</span> <span class="fu">list</span>(</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">lm =</span> <span class="fu">caretModelSpec</span>(<span class="at">method =</span> <span class="st">"lm"</span>),</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">tree =</span> <span class="fu">caretModelSpec</span>(<span class="at">method =</span> <span class="st">"ctree2"</span>),</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">rf =</span> <span class="fu">caretModelSpec</span>(<span class="at">method =</span> <span class="st">"rf"</span>, <span class="at">tuneGrid =</span> grid_rf),</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">steplm =</span> <span class="fu">caretModelSpec</span>(<span class="at">method =</span> <span class="st">"glmStepAIC"</span>, <span class="at">direction =</span> <span class="st">"both"</span>),</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">elastic =</span> <span class="fu">caretModelSpec</span>(<span class="at">method =</span> <span class="st">"glmnet"</span>, <span class="at">tuneLength =</span> <span class="dv">10</span>),</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">mars =</span> <span class="fu">caretModelSpec</span>(<span class="at">method =</span> <span class="st">"earth"</span>, <span class="at">tuneGrid =</span> grid_mars),</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">svm =</span> <span class="fu">caretModelSpec</span>(<span class="at">method =</span> <span class="st">"svmRadial"</span>, <span class="at">tuneGrid =</span> grid_svm)</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
summary.resamples(object = results)

Models: lm, tree, rf, steplm, elastic, mars, svm 
Number of resamples: 30 

MAE 
             Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's
lm      0.2507026 0.2883965 0.3066584 0.3096262 0.3322125 0.3745525    0
tree    0.2620396 0.2812451 0.3041561 0.3056309 0.3256438 0.3658560    0
rf      0.2890655 0.3228814 0.3362971 0.3372919 0.3531122 0.3796401    0
steplm  0.2510672 0.2885842 0.3065320 0.3093471 0.3300426 0.3731281    0
elastic 0.2677744 0.3039028 0.3217938 0.3218742 0.3402905 0.3807083    0
mars    0.2326313 0.2633429 0.2814794 0.2849499 0.3075828 0.3616377    0
svm     0.1783768 0.2094752 0.2478449 0.2450854 0.2773623 0.3038932    0

RMSE 
             Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's
lm      0.3108286 0.3601003 0.3767458 0.3821889 0.4082127 0.4681236    0
tree    0.3330157 0.3700080 0.3990558 0.4015311 0.4314378 0.4741237    0
rf      0.3216688 0.3605741 0.3743362 0.3767851 0.3967032 0.4318399    0
steplm  0.3107060 0.3596958 0.3766486 0.3813651 0.4062587 0.4666710    0
elastic 0.3180720 0.3664884 0.3797979 0.3830307 0.4053065 0.4577907    0
mars    0.3110097 0.3451877 0.3823228 0.3765549 0.3995850 0.4697700    0
svm     0.2762220 0.3285268 0.3646287 0.3643587 0.4000208 0.4390519    0

Rsquared 
             Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's
lm      0.1813602 0.3528101 0.4269555 0.4117600 0.4824382 0.6202011    0
tree    0.1669185 0.2880606 0.3605231 0.3592114 0.4416148 0.5743444    0
rf      0.2529640 0.4204137 0.4952467 0.4830752 0.5531362 0.6866644    0
steplm  0.1849282 0.3587717 0.4233000 0.4143251 0.4823253 0.6210330    0
elastic 0.1843338 0.3628461 0.4298010 0.4144680 0.4805138 0.6308119    0
mars    0.1952596 0.3674161 0.4143845 0.4336043 0.5197909 0.6279966    0
svm     0.2884767 0.3762828 0.4768066 0.4719783 0.5560446 0.6913278    0</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PortfolioWithPictures_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>R^2 will be the metric of use to compare the created regression models. On average the model that performed the best with this metric is the random forest model.</p>
</section>
<section id="random-forest-deep-dive" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-deep-dive">Random Forest Deep Dive</h3>
<p><img src="images/1_Mb8awDiY9T6rsOjtNTRcIg.png" class="img-fluid"></p>
<p>Random Forest Regression combines the strength of multiple decision trees to create a reliable and accurate model, making it a popular choice in various real-world applications.</p>
<p>The created model in the caretList() function will be expanded upon below.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>m3_rf<span class="sc">$</span>bestTune</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mtry
2    4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>m3_rf<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mtry      RMSE  Rsquared       MAE     RMSESD RsquaredSD      MAESD
1    1 0.3775385 0.4826302 0.3374380 0.02060801 0.09242631 0.01665676
2    4 0.3646173 0.4676522 0.2763640 0.03392727 0.10313997 0.02512311
3    7 0.3698914 0.4515148 0.2747749 0.03669477 0.10852965 0.02648622
4   10 0.3731106 0.4415982 0.2734693 0.03849614 0.11112556 0.02852233</code></pre>
</div>
</div>
<p>The model tuned for four performed the best.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>m3_rf <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(HeartDisease <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in randomForest.default(m, y, ...): The response has five or fewer
unique values.  Are you sure you want to do regression?</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get variable importance</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>var_importance <span class="ot">&lt;-</span> <span class="fu">importance</span>(m3_rf)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame with variable names and importance scores</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>var_importance_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">rownames</span>(var_importance),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Importance =</span> var_importance[, <span class="dv">1</span>]  <span class="co"># Using MeanDecreaseGini</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordering the data frame by importance</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>var_importance_df <span class="ot">&lt;-</span> var_importance_df[<span class="fu">order</span>(var_importance_df<span class="sc">$</span>Importance, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(var_importance_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Variable, Importance), <span class="at">y =</span> Importance)) <span class="sc">+</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"#2E75B6"</span>) <span class="sc">+</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Predictor Variable"</span>, <span class="at">y =</span> <span class="st">"Performance in Nodes"</span>, <span class="at">title =</span> <span class="st">"Variable Importance Plot"</span>) <span class="sc">+</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="PortfolioWithPictures_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Variable Importance Plots generated above shows the order of importance of each variable in the forest. Variables such as cholestoral, max heart rate, and exercised induced chest pain were among the most important variables. Variables such as gender, colored vessels in a fluoroscopy, as well as hypertrophy did not appear to have much importance.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>In conclusion, both the classification and regression models were able to predict heart disease and the chance of developing heart diseases about 50% of the time. The strongest Known-Nearest-Neighbor Model had a kappa of about .55. The fine-tuned random forest generated a mean R^2 value of about .46. These two outcomes are very close to random chance, as a coin flip of guessing if an individual has heart disease would result in a fifty fifty chance. Literature suggests that diagnosing an individual with heart disease is difficult. This is because, heart disease symptoms are not always straightforward. While chest pain (angina) is a common sign, some people experience atypical symptoms such as shortness of breath, pain in the neck, jaw, throat, upper belly area, or back, and numbness or weakness in the legs or arms, many of these symptoms are contributed to other diseases as well. Heart disease encompasses various conditions, including coronary artery disease, cardiomyopathy, and heart failure. Each type may present differently, making it harder to pinpoint the exact cause.</p>
<p>These factors explain why generating consistent models close to fifty percent accuracy is not as diminishing as it seems on paper. For future analysis, a larger data set would be more ideal, as machine learning usually suggests thousands of observations, and there were only 920. NA variables had to be replaced or else there would be only 268 observations to make models from. If there were variables in the dataset, such as smoking, or familial status with heart disease, that might also make classification and regression models perform stronger.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>